### ISSUE TITLE
Sticky behavior on mobile

### ISSUE THREAD

**Issue by timzolleis** [l-mbert/dns-checker#1]
Hi there! First of all, thank you for your great project! Finally a DNS checker that is carefully designed! 

Regarding the sticky layout on mobile, I personally find it hard to distinguish the elements (and it looks like the layout is "buggy" even tho it isn't) - Screenshot attached.

![image](https://github.com/l-mbert/dns-checker/assets/95548013/4644b7ff-abdf-40dc-8c3b-96320ca0a8b5)

I do have two ideas, but i'd love to get your opinion first, since you clearly thought well about the design.

- Create a "drawer" or sticky element with fixed background that will stick to the top of the screen when scrolled

- Put the Input in a drawer that's on the bottom of the page on mobile (something like Emil Kowalskis Vaul)

Let me know if this is something that makes sense! I'd be more than happy to craft some prototypes and provide you with a PR.

Sincerely,

**Comment by l-mbert** [comment]
Hi, thanks for the flowers!

This was a bug which I noticed when showing it to a friend and it's fixed but I like the general idea of having the main controls sticky.

Personally I would put it at the bottom, probably looking similar to the address bar of safari with a little more spacing.
When clicking it it would open up a Vaul drawer and show the options there but I'm open to suggestions!

You can give it a shot if you'd like!

**Comment by l-mbert** [comment]
Thank you!
